---
- name: Set httpd_sys_rw_content_t context to mediawiki directory
  community.general.sefcontext:
    target: "{{ wiki_install_dir }}"
    setype: httpd_sys_rw_content_t
    state: present
  notify: Apply Restorecon

- name: Set httpd_sys_rw_content_t context to wordpress directory
  community.general.sefcontext:
    target: "{{ wp_install_dir }}"
    setype: httpd_sys_rw_content_t
    state: present
  notify: Apply Restorecon
