---
- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Reload Firewall
  service:
    name: firewalld
    state: reloaded

- name: Restart Dovecot
  service:
    name: dovecot
    state: restarted
