---
- name: Create deployment directory for WordPress
  file:
    path: "{{ wp_install_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: Download and unpack WordPress packages
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "{{ wp_install_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ wp_install_dir }}/index.php"
    owner: nginx
    group: nginx

- name: Create Nginx configuration
  template:
    src: wordpress.nginx.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
  notify: Reload Nginx Server
