---

## Project

project_directory: "/home/student/ansible-github-deployment-automation/nexcore-infra"
domain_name: "nexcore.local"
network_subnet: "172.25.250.0/24"

# DNS

dns_server_fqdn: "dns.{{ domain_name }}"
dns_server_ip: "{{ hostvars[groups['dns_server'][0]]['ansible_host'] }}"
dns_admin_user: "admin"

mail_server_fqdn: "mail.{{ domain_name }}"
mail_server_ip: "{{ hostvars[groups['mail_server'][0]]['ansible_host'] }}"

db_server_fqdn: "db.{{ domain_name }}"
db_server_ip: "{{ hostvars[groups['db_server'][0]]['ansible_host'] }}"

wiki_server_ip: "{{ hostvars[groups['wiki_server'][0]]['ansible_host'] }}"
wordpress_server_ip: "{{ hostvars[groups['wp_server'][0]]['ansible_host'] }}"
nfs_server1_ip: "{{ hostvars[groups['nfs_servers'][0]]['ansible_host'] }}"

## NFS

storage_mount_point: "/mnt/shared"
storage_vg_name: "vg_shared"
storage_lv_name: "lv_shared"
storage_lv_size: "1000M"
storage_dev_disk: "/dev/vdb"
dev_group_gid: "3000"

## Users

local_key_dir: "{{ project_directory }}/roles/users/keypairs"

managed_users:
  - username: "ops01"
    groups: "ops"
    sudo: true
  - username: "dev01"
    groups: "dev"
    sudo: false
  - username: "dev02"
    groups: "dev"
    sudo: false
  - username: "mkt01"
    groups: "marketing"
    sudo: false

## Logging

log_server: "{{ hostvars[groups['log_server'][0]]['ansible_host'] }}"
