## MediaWiki

wiki_db_name: "media_wiki_db"
wiki_db_user: "mediawiki"
wiki_db_password: "Med1aW1k12027!"

## Wordpress
wp_db_name: "wordpressdb"
wp_db_user: "wpuser"
wp_db_password: "WordPre551999#"

## Backups
backup_db_user: "backup"
backup_user_password: "BackupGuy1678!?"
