[web]
servera ansible_host=servera.nexcore.local

[db]
serverb ansible_host=serverb.nexcore.local

[nfs_clients]
servera ansible_host=servera.nexcore.local
serverc ansible_host=serverc.nexcore.local

[nfs_servers]
serverb ansible_host=serverb.nexcore.local

[all_managed:children]
web
db
nfs_clients
nfs_servers
