[localhost]
localhost

[db_server]
serverb

[wiki_server]
servera

[wp_server]
servera

[nfs_clients]
servera
serverc

[nfs_servers]
serverb

[dns_server]
servera

[mail_server]
serverb

[all_managed:children]
localhost
wiki_server
wp_server
nfs_clients
nfs_servers
dns_server
mail_server
