servera  ansible_host=172.25.250.10
serverb  ansible_host=172.25.250.11
serverc  ansible_host=172.25.250.12

[db_server]
serverb

[mail_server]
serverb

[nfs_servers]
serverb

[dns_server]
servera

[wiki_server]
servera

[wp_server]
servera

[web_servers:children]
wiki_server
wp_server

[nfs_clients]
servera
serverc

[all_managed:children]
web_servers
db_server
mail_server
nfs_clients
nfs_servers
dns_server
