---
- name: Patch Ansible on Localhost
  pip:
    name: ansible
    state: latest
    executable: pip3

- name: Configure security
  hosts: all_managed
  become: true
  roles:
    - security
  tags: configure_security
  vars_files:
    - group_vars/web.yml

- name: Configure users
  hosts: all_managed
  become: true
  roles:
    - users
  tags: configure_users

- name: Deploy MySQL Database
  hosts: db_server
  become: true
  roles:
    - database
  tags: deploy_mysql
  vars_files:
#    - group_vars/all.yml
    - group_vars/db.yml
    
- name: Configure BIND on DNS server and resolv.conf on clients
  hosts: all_managed
  become: true
  roles:
    - dns
  tags: deploy_dns

- name: Configure NFS
  hosts: all_managed
  become: true
  roles:
    - storage
  tags: configure_nfs

- name: Configure MediaWiki and Nginx
  hosts: wiki_server
  become: true
  roles:
    - web
    - wiki
  tags: deploy_wiki
  vars_files:
    - group_vars/db.yml
    - group_vars/web.yml

- name: Configure Wordpress and Nginx
  hosts: wp_server
  become: true
  roles:
    - web
    - wordpress
  tags: deploy_wp
  vars_files:
    - group_vars/db.yml
    - group_vars/web.yml

- name: Configure Postfix
  hosts: mail_server
  become: true
  roles:
    - email
  tags: deploy_email

- name: Configure Logging
  hosts: all_managed
  become: true
  roles:
    - logging
  tags: configure_logging

- name: Configure Patching
  hosts: all_managed
  become: true
  roles:
    - patching
  tags: configure_patching
