---
- name: Deploy MySQL Database
  hosts: db_server
  become: true
  roles:
    - database

- name: Configure BIND on DNS server and resolv.conf on clients
  hosts: all_managed
  become: true
  roles:
    - dns

- name: Configure NFS
  hosts: all_managed
  become: true
  roles:
    - storage

- name: Configure MediaWiki and Nginx
  hosts: wiki_server
  become: true
  roles:
    - wiki
    - web

- name: Configure Wordpress and Nginx
  hosts: wp_server
  become: true
  roles:
    - wiki
    - web
