---
- name: Install MySQL Server and PyMySQL dependencies
  dnf:
    name:
      - mysql-server
    state: present

- name: Start and enable MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Allow mysql service port in firewall
  ansible.posix.firewalld:
    service: mysql
    permanent: true
    state: enabled
    immediate: true

- name: Create the dedicated MediaWiki database
  ansible.mysql.mysql_db:
    name: "{{ wiki_db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create remote MySQL user assigned to servera
  ansible.mysql.mysql_user:
    name: "{{ wiki_db_user }}"
    password: "{{ wiki_db_password }}"
    priv: "{{ wiki_db_name }}.*:ALL"
#    host: "servera.nexcore.local"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
