---
- name: Install MySQL Server and PyMySQL
  dnf:
    name:
      - mysql-server
      - python3-PyMySQL
    state: present

- name: Enable MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Configure mysql to listen on subnet
  template:
    src: bind-address.j2
    dest: /etc/my.cnf.d/bind.cnf
    owner: root
    group: mysql
    mode: '0640'
  notify: Restart MySQL

- name: Create the dedicated MediaWiki database
  ansible.mysql.mysql_db:
    name: "{{ wiki_db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create remote MySQL user assigned to mediawiki
  ansible.mysql.mysql_user:
    name: "{{ wiki_db_user }}"
    password: "{{ wiki_db_password }}"
    priv: "{{ wiki_db_name }}.*:ALL"
    state: present
    host: "{{ wiki_server_ip }}"
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create the dedicated Wordpress database
  ansible.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create remote MySQL user assigned to wordpress
  ansible.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ wordpress_server_ip }}"
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create MySQL user assigned to backups
  ansible.mysql.mysql_user:
    name: "{{ backup_db_user }}"
    password: "{{ backup_user_password }}"
    priv: "*.*:ALL"
    state: present
    host: "localhost"
    login_unix_socket: /var/lib/mysql/mysql.sock
