---
- name: Configure Apache
  import_tasks: apache.yml

- name: Configure wiki.nexcore.local virtual host
  import_tasks: wiki.yml
  when: inventory_hostname in groups['wiki_server']

- name: Configure www.nexcore.local virtual host
  import_tasks: wordpress.yml
  when: inventory_hostname in groups['wp_server']
