---
- name: Create backups directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Nightly database backups to backup directory
  template:
    src: backup.sh.j2
    dest: /usr/local/bin/backup.sh

- name: Configure CRON to run backup nightly
  cron:
    name: "Nighlty Database Backup"
    minute: "0"
    hour: "1"
    job: "/usr/local/bin/backup.sh"
