---
- name: Install NFS utils
  dnf:
    name: nfs-utils
    state: present

- name: Make sure dev group exists on client
  group:
    name: dev
    gid: "{{ dev_group_gid }}"
    state: present

- name: Create mount point on client
  file:
    path: "{{ storage_mount_point }}"
    state: directory
    mode: '2775'

- name: Mount the shared directory from NFS server
  ansible.posix.mount:
    path: "{{ storage_mount_point }}"
    src: "{{ nfs_server1_ip }}:{{storage_mount_point }}"
    fstype: nfs
    opts: rw,sync
    state: mounted

- name: Install AutoFS on clients
  dnf:
    name: autofs
    state: present

- name: Configure AutoFS master mapping rule
  template:
    src: company_share.j2
    dest: /etc/auto.master.d/company_share.master.autofs
    owner: root
    group: root
    mode: '0644'
  notify: Restart AutoFS

- name: Deploy company_share mapping file
  template:
    src: auto.company_share.j2
    dest: /etc/auto.company_share
    owner: root
    group: root
    mode: '0644'
  notify: Restart AutoFS

- name: Start and enable AutoFS on clients
  service:
    name: autofs
    state: started
    enabled: true
