---
- name: Configure NFS Share on NFS Server
  import_tasks: server.yml
  when: inventory_hostname in groups['nfs_servers']

- name: Configure NFS Share on Clilents
  import_tasks: client.yml
  when: inventory_hostname in groups['nfs_clients']

- name: Configure AutoFS on Clients
  import_tasks: autofs.yml
  when: inventory_hostname in groups['nfs_clients']
