---
- name: Install LVM2 and NFS server utilities
  dnf:
    name:
      - lvm2
      - nfs-utils
    state: present

- name: Initialize Volume Group and Physical Volume
  lvg:
    vg: "{{ storage_vg_name }}"
    pvs: "{{ storage_dev_disk }}"
    state: present

- name: Create Logical Volume inside Volume Group
  lvol:
    vg: "{{ storage_vg_name }}"
    lv: "{{ storage_lv_name }}"
    size: "{{ storage_lv_size }}"
    state: present

- name: Format with XFS file system
  filesystem:
    fstype: xfs
    dev: "/dev/{{ storage_vg_name }}/{{ storage_lv_name }}"

- name: Make sure dev group exists
  group:
    name: dev
    gid: "{{ dev_group_gid }}"
    state: present

- name: Create mount target directory
  file:
    path: "{{ storage_mount_point }}"
    state: directory
    mode: '2775'

- name: Mount the Logical Volume
  ansible.posix.mount:
    path: "{{ storage_mount_point }}"
    src: "/dev/{{ storage_vg_name }}/{{ storage_lv_name }}"
    fstype: xfs
    state: mounted

- name: Allow read write and execute to dev group
  file:
    path: "{{ storage_mount_point }}"
    owner: root
    group: dev
    mode: '2775'

- name: Configure NFS exports table file
  template:
    src: exports.j2
    dest: /etc/exports
  notify: Reload NFS Exports Table

- name: Start and enable NFS server
  service:
    name: nfs-server
    state: started
    enabled: true

- name: Unblock internal network firewall for NFS, mountd and rpc-bind
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - nfs
    - mountd
    - rpc-bind

- name: Provision per user storage
  file:
    path: "/mnt/shared/users/{{ item.username }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.groups }}"
    mode: '2700'
  loop: "{{ managed_users }}"
